### ISSUE TITLE
Further Development of the Tech Conference Page

### ISSUE THREAD

**Issue by roniy68** [Timbar09/Africas-Leading-Tech-Conference#6]
# Highlights 🟢 
- Linters ✅ 
- Documentation ✅ 
- HTML, CSS & JS common development flow ✅ 

![issue](https://media.giphy.com/media/1heVzkRdSed56/giphy.gif)

# Some Issues that can be upgraded 🔴 

- [ ] 404 on clicking the home ICON

# Optional suggestion

- [ ] You can add a social icons top bar before the Main__Header as the design suggests
- [ ] You also add another menu for home page

**Comment by Timbar09** [comment]
I have made the corrections.

Thanks, @roniy68
